### ISSUE TITLE
How to translate strings with wp.i18n

### ISSUE THREAD

**Issue by StefanoMarchesi** [crossfield/gutenblock#14]
I've read in the readme that you are working on an automated translation system with i18n but what about current situation? How can i manage I18n translation in gutenblock? Even a manual and slow way would be good to go

**Comment by zackify** [comment]
For now, you can do `const {__} = wp.i18n;` anywhere in your block and use the `__()` method. Where are you wanting i18n at? If it's input field labels and placeholders, i can add it to those components automatically. But within your own block you will need to use the i18n function wordpress provides

**Comment by StefanoMarchesi** [comment]
Thank you very much, for me it's mainly in my custom blocks so the `const {__} = wp.i18n;` will be perfect
