### ISSUE TITLE
InspectorControls

### ISSUE THREAD

**Issue by timarney** [crossfield/gutenblock#15]
Looks like InspectorControls is now under wp.editor . Not sure when that changed.

```
wp.editor.InspectorControls
```

Breaks:
```
const { InspectorControls } = wp.blocks;
```

**Comment by zackify** [comment]
Thanks, we are pinned to a version back for this client now, I can add a fix for this later today

**Comment by zackify** [comment]
Sorry about not getting to the other ones, been low priority for me :(

**Comment by timarney** [comment]
No worries.

**Comment by timarney** [comment]
Looks like this applies to RichText as well wp.editor.RichText

**Comment by zackify** [comment]
Working on this now!

**Comment by zackify** [comment]
https://github.com/crossfield/gutenblock/releases/tag/1.0.0 

Should be all set, I am continuing to test on our site

**Comment by timarney** [comment]
Nice thanks for turning that around :) my blocks work again now.
