### ISSUE TITLE
Use with npx?

### ISSUE THREAD

**Issue by jasonbahl** [crossfield/gutenblock#2]
First, thanks for working on this. Looks like a great project that will be super useful!

Lately I've been using `npx` to run scripts instead of installing globally. I tried with this (`npx gutenblock init`), and it didn't work. I did install globally and run and it's working. 

Not sure what it takes to work with `npx` but would be cool if it worked.

**Comment by zackify** [comment]
it should be able to run with npx, all that does is cause it to use the local path like you're saying. I will look into this over the weekend :D

**Comment by jasonbahl** [comment]
again, thinking something is wrong with my environment. . .this seems to work for me today 🤔
