### ISSUE TITLE
Uncaught Error: only one instance of @babel/polyfill is allowed

### ISSUE THREAD

**Issue by jasonbahl** [crossfield/gutenblock#3]
Hey, I've not been able to get this up and running. With both the `gutenblock watch` and `gutenblock build` I get:

```
index.js:8 Uncaught Error: only one instance of @babel/polyfill is allowed
    at Object.eval (index.js:8)
    at eval (index.js:12)
    at Object.../node_modules/@babel/polyfill/lib/index.js (main.js?ver=4.9.5:1253)
    at __webpack_require__ (main.js?ver=4.9.5:753)
    at fn (main.js?ver=4.9.5:122)
    at eval (client:2)
    at Object.1 (main.js?ver=4.9.5:5093)
    at __webpack_require__ (main.js?ver=4.9.5:753)
    at main.js?ver=4.9.5:873
    at main.js?ver=4.9.5:876
```

Thoughts?

**Comment by zackify** [comment]
Your code must import @babel/polyfill somewhere. I should probably make it opt-in so you have to include it yourself like you are.

**Comment by jasonbahl** [comment]
@zackify all I’ve done so far is install the script and try to make one block following your video but i get this error and no block.

No custom code yet. 

I’ll try from scratch again just to be sure and report back

**Comment by zackify** [comment]
Dang, feel really bad about this. If you could, upload it to a repo for me. I really want to find out what’s wrong here

**Comment by jasonbahl** [comment]
@zackify don’t feel bad. Happy that you shared your project and are helping push WordPress forward.

Is the gutenberg-controls npm package on Github anywhere?

**Comment by jasonbahl** [comment]
So, I ran through in another WordPress environment and all is working fine. Not sure what I was doing wrong in my other environment, but seems like things are working now. I'll close as this appears to be an environmental issue on my end.

**Comment by zackify** [comment]
Yes, you can install gutenberg-controls by itself. Also working on building out more useful controls for it too! 

Glad you got it working :D

**Comment by jasonbahl** [comment]
@zackify so, it looks like this is an issue when Yoast SEO is active alongside this. That's why I was able to get it working in my other fresh environment. 

Not sure what the solution is, but seems like it still probably is an issue worth looking into.

**Comment by zackify** [comment]
Makes sense. I’ll make sure to remove the polyfill by default. I’ll do this Sunday. For now you can edit the base.config.js in your node modules (in config folder) and remove the entry point

**Comment by zackify** [comment]
https://github.com/crossfield/gutenblock/releases/tag/0.4.0

Should be good to go
