### ISSUE TITLE
MySql error on starting Docker

### ISSUE THREAD

**Issue by kazlan** [crossfield/gutenblock#5]
When running gutenblock watch docker I get the following error and cant seem to find a solution.

`wordpress_1  | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
wordpress_1  |
wordpress_1  | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22`

I'm on osx High sierra. Any idea?

**Comment by zackify** [comment]
This is my bad, a new mysql version came out and i was pinned to latest, will fix tomorrow.

**Comment by zackify** [comment]
Just fixed! https://github.com/crossfield/gutenblock/releases/tag/0.4.1

**Comment by kazlan** [comment]
Solved one but fell into another. Looks like InnoDB plugin is not loading and db_1 collapses.
`db_1         | 2018-04-24 10:04:31 0 [Note] mysqld (mysqld 5.6.40) starting as process 1 ...
db_1         | 2018-04-24 10:04:31 1 [Note] Plugin 'FEDERATED' is disabled.
db_1         | mysqld: Table 'mysql.plugin' doesn't exist
db_1         | 2018-04-24 10:04:31 1 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: The InnoDB memory heap is disabled
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Memory barrier is not used
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Using Linux native AIO
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Using CPU crc32 instructions
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2018-04-24 10:04:31 1 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | InnoDB: No valid checkpoint found.
db_1         | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
db_1         | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
db_1         | InnoDB: If this error appears when you are creating an InnoDB database,
db_1         | InnoDB: the problem may be that during an earlier attempt you managed
db_1         | InnoDB: to create the InnoDB data files, but log file creation failed.
db_1         | InnoDB: If that is the case, please refer to
db_1         | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
db_1         | 2018-04-24 10:04:31 1 [ERROR] Plugin 'InnoDB' init function returned error.
db_1         | 2018-04-24 10:04:31 1 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1         | 2018-04-24 10:04:31 1 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1         | 2018-04-24 10:04:31 1 [ERROR] Aborting
db_1         |
db_1         | 2018-04-24 10:04:31 1 [Note] Binlog end
`

**Comment by zackify** [comment]
Try “docker system prune” before running the watcher again
